packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/subgraph'
  - 'sdk/typescript'
  - 'cli'
allowBuilds:
  '@reown/appkit': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  bufferutil: true
  core-js-pure: true
  esbuild: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
  utf-8-validate: true
