/**
 * Kokonut Agent SDK - ABI Definitions
 * Shared ABI constants for all SDK modules
 */

import { parseAbi } from 'viem';

export const IDENTITY_REGISTRY_ABI = parseAbi([
  'function register(string agentURI) external returns (uint256 agentId)',
  'function getAgent(uint256 agentId) external view returns (address owner, string memory agentURI, address agentWallet, bool isActive)',
  'function isAgent(address agentAddress) external view returns (bool)',
  'function getCurrentAgentId() external view returns (uint256)',
  'function setAgentURI(uint256 agentId, string calldata newURI) external',
  'function getMetadata(uint256 agentId, string calldata metadataKey) external view returns (bytes memory)',
  'function setMetadata(uint256 agentId, string calldata metadataKey, bytes calldata metadataValue) external',
  'function getAgentWallet(uint256 agentId) external view returns (address)',
  'function setAgentWallet(uint256 agentId, address newWallet, uint256 deadline, bytes calldata signature) external',
  'function unsetAgentWallet(uint256 agentId) external',
  'event Registered(uint256 indexed agentId, string agentURI, address indexed owner)',
  'event AgentURIUpdated(uint256 indexed agentId, string newURI)',
  'event MetadataUpdated(uint256 indexed agentId, string key)',
  'event AgentWalletUpdated(uint256 indexed agentId, address indexed oldWallet, address indexed newWallet)',
] as const);

export const LEGACY_REPUTATION_ABI = parseAbi([
  'function submitFeedback(address agent, uint256 taskId, int256 rating, string calldata metadataURI) external returns (uint256)',
  'function getAgentReputation(address agent) external view returns (int256 average, uint256 total, uint256 providers)',
] as const);

export const SERVICE_REGISTRY_ABI = parseAbi([
  'function createService(uint256 agentId, string calldata name, string calldata description, string calldata metadataURI, uint256 price, address paymentToken) external returns (uint256 serviceId)',
  'function updateService(uint256 serviceId, string calldata name, string calldata description, string calldata metadataURI, uint256 price) external',
  'function deactivateService(uint256 serviceId) external',
  'function activateService(uint256 serviceId) external',
  'function getService(uint256 serviceId) external view returns ((uint256 id, address provider, uint256 agentId, string name, string description, string metadataURI, uint256 price, address paymentToken, bool isActive, uint256 createdAt))',
  'function getServices(uint256 start, uint256 count) external view returns (uint256[] memory)',
  'function getActiveServiceCount() external view returns (uint256)',
  'function getProviderServices(address provider) external view returns (uint256[] memory)',
  'function getServicesByAgent(uint256 agentId) external view returns (uint256[] memory)',
  'function getServiceCounter() external view returns (uint256)',
  'event ServiceCreated(uint256 indexed serviceId, address indexed provider, uint256 indexed agentId, string name, uint256 price)',
  'event ServiceUpdated(uint256 indexed serviceId)',
  'event ServiceDeactivated(uint256 indexed serviceId)',
  'event ServiceActivated(uint256 indexed serviceId)',
] as const);

export const AGENTIC_COMMERCE_ABI = parseAbi([
  'function createJob(address provider, uint256 budget, address paymentToken, uint256 serviceId, uint256 expiredAt, string calldata description, address evaluator, address hook, bool evaluatorFee, bool clientReview_, bool fundNow, uint256 fundAmount) external payable returns (uint256 jobId)',
  'function createJobV7(address provider, address evaluator, uint256 expiredAt, string calldata description, address hook, bool evaluatorFee, bool clientReview) external returns (uint256 jobId)',
  'function createJobWithRandomEvaluator(address provider, uint256 expiredAt, string calldata description, address hook, bool evaluatorFee, bool clientReview) external returns (uint256 jobId)',
  'function setBudget(uint256 jobId, uint256 amount) external',
  'function fund(uint256 jobId, uint256 expectedBudget) external payable',
  'function submit(uint256 jobId, bytes32 deliverable) external',
  'function reject(uint256 jobId, bytes32 reason) external',
  'function claimRefund(uint256 jobId) external',
  'function refundExpired(uint256 jobId) external',
  'function completeAfterTimeout(uint256 jobId, bytes32 reason) external',
  'function setDisputeWindow(uint256 jobId, uint256 window) external',
  'function setNonResponsiveSlashBP(uint256 jobId, uint256 slashBP) external',
  'function approveByClient(uint256 jobId) external',
  'function finalizeByEvaluator(uint256 jobId, bytes32 reason) external',
  'function setPaymentToken(uint256 jobId, address paymentToken) external',
  'function getMinBudget(address token, uint8 decimals) external view returns (uint256)',
  'function setMinBudgetUsd(uint256 newMin) external',
  'function setMaxBudgetUsd(uint256 newMax) external',
  'function setMinBudgetOverride(address token, uint256 minAmount) external',
  'function setStablecoin(address token, bool isStable) external',
  'function setPriceOracle(address _priceOracle) external',
  'function maxBudgetUsd() external view returns (uint256)',
  'function registerAsEvaluator() external payable',
  'function unregisterAsEvaluator() external',
  'function cleanupStaleEvaluators(uint256 maxIterations) external returns (uint256 removedCount)',
  'function getEvaluatorPoolSize() external view returns (uint256)',
  'function finalizeRandomEvaluator(uint256 jobId) external',
  'function slashEvaluatorStake(address evaluator, string calldata reason) external',
  'function jobs(uint256) external view returns (uint256 id, address client, address provider, address evaluator, uint256 serviceId, address paymentToken, string description, uint256 budget, uint256 expiredAt, uint8 status, address hook, bytes32 deliverable)',
  'function jobCounter() external view returns (uint256)',
  'function getClientJobCount(address client) external view returns (uint256)',
  'function isEvaluatorFeeEnabled(uint256 jobId) external view returns (bool)',
  'function isEvaluator(address account) external view returns (bool)',
  'function evaluatorStakes(address evaluator) external view returns (uint256)',
  'function evaluatorCommits(uint256 jobId) external view returns (bytes32 commitHash, uint256 commitBlock, bool revealed)',
  'function jobCreationBlock(uint256 jobId) external view returns (uint256)',
  'function hasClientApproved(uint256 jobId) external view returns (bool)',
  'function isClientReviewRequired(uint256 jobId) external view returns (bool)',
  'function minBudgetUsd() external view returns (uint256)',
  'function minBudgetOverride(address token) external view returns (uint256)',
  'function isStablecoin(address token) external view returns (bool)',
  'function allowedTokens(address token) external view returns (bool)',
  'function priceOracle() external view returns (address)',
  'function paused() external view returns (bool)',
  'function setPlatformTreasury(address treasury) external',
  'function setAdminRegistry(address _adminRegistry) external',
  'function setAllowedToken(address token, bool allowed) external',
  'function pause() external',
  'function unpause() external',
  'event JobCreated(uint256 indexed jobId, address indexed client, address indexed provider, address evaluator, uint256 serviceId, uint256 expiredAt, bool evaluatorFee, bool clientReview, bool randomEvaluator)',
  'event BudgetSet(uint256 indexed jobId, uint256 amount)',
  'event JobFunded(uint256 indexed jobId, address indexed client, uint256 amount)',
  'event JobSubmitted(uint256 indexed jobId, address indexed provider, bytes32 deliverable)',
  'event JobCompleted(uint256 indexed jobId, address indexed by, address indexed provider, uint256 evaluatorFee)',
  'event PaymentReleased(uint256 indexed jobId, uint256 providerAmount, uint256 platformFee, uint256 evaluatorFee)',
  'event JobRejected(uint256 indexed jobId, address indexed rejector, bytes32 reason)',
  'event Refunded(uint256 indexed jobId, address indexed client, uint256 amount)',
  'event PermissionlessRefund(uint256 indexed jobId, address indexed client, address indexed caller, uint256 amount)',
  'event JobExpired(uint256 indexed jobId)',
  'event JobStatusChanged(uint256 indexed jobId, uint8 oldStatus, uint8 newStatus, address changedBy, uint256 timestamp)',
  'event DisputeWindowSet(uint256 indexed jobId, uint256 window)',
  'event NonResponsiveSlashSet(uint256 indexed jobId, uint256 slashBP)',
  'event EvaluatorSlashedForInactivity(uint256 indexed jobId, address indexed evaluator, uint256 slashAmount)',
  'event StaleEvaluatorsCleaned(uint256 removedCount)',
  'event EvaluatorSlashed(address indexed evaluator, uint256 stake, string reason)',
  'event PlatformTreasurySet(address indexed oldTreasury, address indexed newTreasury)',
  'event AdminRegistrySet(address indexed oldRegistry, address indexed newRegistry)',
  'event PriceOracleSet(address indexed oldOracle, address indexed newOracle)',
  'event MaxBudgetChanged(uint256 oldMax, uint256 newMax)',
] as const);

export const USDC_ABI = parseAbi([
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function balanceOf(address account) external view returns (uint256)',
  'function allowance(address owner, address spender) external view returns (uint256)',
] as const);

export const MILESTONE_ESCROW_ABI = parseAbi([
  'function initialize(address initialOwner, address _agenticCommerce) external',
  'function setAgenticCommerce(address _agenticCommerce) external',
  'function agenticCommerce() external view returns (address)',
  'function setArbiterFee(address token, uint256 fee) external',
  'function setArbiterStake(address token, uint256 stake) external',
  'function setSupportedToken(address token, bool supported) external',
  'function SLASH_PERCENT() external view returns (uint256)',
  'function MAX_MILESTONES_PER_JOB() external view returns (uint256)',
  'function ARBITER_RESPONSE_WINDOW() external view returns (uint256)',
  'function enableMilestones(uint256 jobId, address client, address provider, address paymentToken, uint256 totalBudget) external',
  'function addMilestone(uint256 jobId, uint256 amount, string calldata description, uint256 dueDate) external',
  'function fundMilestones(uint256 jobId, uint256 amount) external payable',
  'function submitMilestone(uint256 jobId, uint256 milestoneIndex, bytes32 proofHash) external',
  'function releaseMilestone(uint256 jobId, uint256 milestoneIndex) external',
  'function getJobMilestones(uint256 jobId) external view returns ((string description, uint256 amount, uint256 dueDate, bool completed, bool released, bytes32 proofHash)[] memory)',
  'function getMilestoneCount(uint256 jobId) external view returns (uint256)',
  'function jobMilestones(uint256) external view returns (address client, address provider, address paymentToken, uint256 totalBudget, bool usesMilestones)',
  'function milestoneEscrowBalance(uint256 jobId) external view returns (uint256)',
  'function milestoneTotalAmount(uint256) external view returns (uint256)',
  'function registerAsArbiter(address token, uint256 amount) external payable',
  'function unregisterAsArbiter() external',
  'function getArbiterStake(address arbiter) external view returns (uint256)',
  'function getArbiterStakeToken(address arbiter) external view returns (address)',
  'function getArbiters() external view returns (address[] memory)',
  'function arbiterPool(uint256) external view returns (address)',
  'function arbiterStakes(address) external view returns (uint256)',
  'function isRegisteredArbiter(address) external view returns (bool)',
  'function slashArbiter(address arbiter, string calldata reason) external',
  'function withdrawToken(address token, uint256 amount) external',
  'function flagDispute(uint256 jobId, uint256 milestoneIndex) external payable',
  'function submitEvidence(uint256 jobId, bytes32 evidenceHash) external',
  'function resolveDispute(uint256 jobId, bool releaseToProvider) external',
  'function getDispute(uint256 jobId) external view returns (uint256 jobId, address flagger, address arbiter, uint256 flaggedAt, bool resolved, bool releaseToProvider, uint256 feePaid, uint256 milestoneIndex)',
  'function getActiveDisputes() external view returns (uint256[] memory)',
  'event MilestoneEnabled(uint256 indexed jobId)',
  'event MilestoneFunded(uint256 indexed jobId, address indexed funder, address token, uint256 amount)',
  'event MilestoneAdded(uint256 indexed jobId, uint256 indexed milestoneIndex, string description, uint256 amount)',
  'event MilestoneCompleted(uint256 indexed jobId, uint256 indexed milestoneIndex, bytes32 proofHash)',
  'event MilestoneReleased(uint256 indexed jobId, uint256 indexed milestoneIndex, uint256 amount)',
  'event MilestoneNotReleased(uint256 indexed jobId, uint256 indexed milestoneIndex, string reason)',
  'event ArbiterRegistered(address indexed arbiter, address token, uint256 stake)',
  'event ArbiterUnregistered(address indexed arbiter, address token, uint256 refundedStake)',
  'event DisputeFlagged(uint256 indexed jobId, address indexed flagger, address token, uint256 fee)',
  'event EvidenceSubmitted(uint256 indexed jobId, address indexed submitter, bytes32 evidenceHash)',
  'event DisputeResolved(uint256 indexed jobId, bool releasedToProvider, address indexed arbiter, address token, uint256 arbiterFee)',
  'event ArbiterSlashed(address indexed arbiter, uint256 slashedAmount, string reason)',
  'event ArbiterAssigned(uint256 indexed jobId, address indexed arbiter)',
] as const);

export const BIDDING_SYSTEM_ABI = parseAbi([
  'function owner() external view returns (address)',
  'function commerce() external view returns (address)',
  'function treasury() external view returns (address)',
  'function revealWindow() external view returns (uint256)',
  'function platformFeeBP() external view returns (uint256)',
  'function sessionCounter() external view returns (uint256)',
  'function getSession(uint256 sessionId) external view returns ((uint256 id, address creator, address evaluator, uint256 maxBudget, uint256 deadline, uint256 revealWindowEnd, bytes metadata, uint256 serviceId, uint256 jobId, address winner, uint256 winningBidId, bool jobCreated, uint8 status))',
  'function getBid(uint256 sessionId, uint256 bidId) external view returns ((uint256 bidId, address bidder, uint256 proposedAmount, uint256 stake, string message, bytes32 commitHash, bool revealed, bool accepted, bool rejected, bool stakeWithdrawn, uint256 timestamp))',
  'function getUserBid(uint256 sessionId, address user) external view returns ((uint256 bidId, address bidder, uint256 proposedAmount, uint256 stake, string message, bytes32 commitHash, bool revealed, bool accepted, bool rejected, bool stakeWithdrawn, uint256 timestamp))',
  'function getSessionCount() external view returns (uint256)',
  'function calculateStake(uint256 maxBudget) external pure returns (uint256)',
  'function createBiddingSession(address evaluator, uint256 maxBudget, uint256 deadline, bytes metadata, uint256 serviceId, address paymentToken) external payable returns (uint256 sessionId)',
  'function commitBid(uint256 sessionId, bytes32 commitHash) external payable',
  'function revealBid(uint256 sessionId, uint256 amount, string message, bytes32 salt) external',
  'function acceptBid(uint256 sessionId, uint256 bidId) external',
  'function rejectBid(uint256 sessionId, uint256 bidId, string reason) external',
  'function withdrawStake(uint256 sessionId) external',
  'function withdrawCreatorStake(uint256 sessionId) external',
  'function completeSession(uint256 sessionId) external',
  'function createJobAndFund(uint256 sessionId, uint256 jobExpiredAt, string description) external payable returns (uint256 jobId)',
  'function cancelSession(uint256 sessionId) external',
  'function extendRevealWindow(uint256 sessionId, uint256 additionalSeconds) external',
  'function setCommerce(address commerce_) external',
  'function setRevealWindow(uint256 window_) external',
  'function setPlatformFeeBP(uint256 basisPoints_) external',
  'function setAdminRegistry(address) external',
  'function setTreasury(address) external',
  'function withdrawPlatformFees(address to, uint256 amount) external',
  'function upgradeTo(address newImplementation) external',
] as const);

export const AGENT_SKILL_REGISTRY_ABI = parseAbi([
  'function registerSkill(uint256 agentId, string calldata name, string calldata version, string calldata description, string calldata endpoint, string[] calldata domains) external returns (uint256 skillId)',
  'function updateSkill(uint256 skillId, string calldata name, string calldata version, string calldata description, string calldata endpoint, string[] calldata domains) external',
  'function getAgentSkills(uint256 agentId) external view returns (uint256[] memory)',
  'function getSkill(uint256 skillId) external view returns ((uint256 agentId, string name, string version, string description, string endpoint, string[] domains, bool isActive, address registeredBy, uint256 registeredAt))',
  'function getSkillData(uint256 skillId) external view returns ((uint256 id, uint256 agentId, string name, string version, string description, string endpoint, string[] domains, bool isActive, address registeredBy, uint256 registeredAt))',
  'function deactivateSkill(uint256 skillId) external',
  'function getTotalSkillCount() external view returns (uint256)',
  'function getAgentSkillCount(uint256 agentId) external view returns (uint256)',
  'function findSkillsByDomain(string calldata domain) external view returns (uint256[] memory)',
  'event SkillRegistered(uint256 indexed agentId, uint256 indexed skillId, string name, string version, address indexed registeredBy)',
  'event SkillUpdated(uint256 indexed skillId, string name, string version)',
  'event SkillDeactivated(uint256 indexed skillId, address indexed deactivatedBy)',
] as const);

export const PRICE_ORACLE_ABI = parseAbi([
  'function getUsdPriceOfToken(address token) external view returns (int256)',
  'function getTokenAmountForUsd(uint256 usdAmount, address token) external view returns (uint256)',
  'function getUsdAmountForTokens(uint256 tokenAmount, address token) external view returns (uint256)',
  'function isStale(address token) external view returns (bool)',
  'function priceFeeds(address token) external view returns (address)',
  'function feedDecimals(address token) external view returns (uint8)',
  'function isStablecoin(address token) external view returns (bool)',
  'function ethPriceFeed() external view returns (address)',
  'function ethFeedDecimals() external view returns (uint8)',
  'function getPriceFeed(address token) external view returns (address)',
  'function getTokenInfo(address token) external view returns (address feed, uint8 decimals, bool stable)',
  'function setPriceFeed(address token, address feed, uint8 decimals) external',
  'function removePriceFeed(address token) external',
  'function setEthPriceFeed(address feed, uint8 decimals) external',
  'function setStablecoin(address token, bool isStable) external',
  'function batchSetPriceFeeds(address[] calldata tokens, address[] calldata feeds, uint8[] calldata decimals_) external',
] as const);

export const COMMIT_REVEAL_ABI = parseAbi([
  'function commit(bytes32 commitment) external',
  'function reveal(string calldata data, uint256 nonce, uint256 serviceId) external',
  'function getCommitment(address user, uint256 nonce) external view returns (bytes32)',
] as const);

export const SLASH_MANAGER_ABI = parseAbi([
  'function createProposal(address evaluator, uint256 proposalId, uint256 amount, string calldata reason) external returns (bytes32)',
  'function confirmProposal(bytes32 proposalId) external',
  'function executeSlash(bytes32 proposalHash) external',
  'function cancelProposal(bytes32 proposalHash) external',
  'function getProposal(bytes32 proposalHash) external view returns (address evaluator, uint256 proposalId, uint256 amount, string reason, uint256 createdAt, uint256 executeAfter, uint256 confirmations, bool executed)',
  'function isSigner(address account) external view returns (bool)',
  'function hasConfirmed(bytes32 proposalHash, address signer) external view returns (bool)',
  'function addSigner(address signer) external',
  'function removeSigner(address signer) external',
  'function setAgentReview(address _agentReview) external',
  'function pause() external',
  'function unpause() external',
] as const);

export const ADMIN_REGISTRY_ABI = parseAbi([
  'function setHalfLifeDays(uint256 halfLifeDays) external',
  'function getHalfLifeDays() external view returns (uint256)',
  'function setFeaturedAgent(uint256 agentId, bool isFeatured) external',
  'function getFeaturedAgents() external view returns (uint256[] memory)',
  'function setVerificationProvider(string provider, bool isActive) external',
  'function getVerificationProviders() external view returns (bool[] memory)',
  'function setSkillRule(string skillName, uint256 minRating, bool isActive) external',
  'function getSkillRules(string skillName) external view returns ((string skillName, uint256 minRating, bool isActive))',
  'function calculateDecayedRating(uint256 initialRating, uint256 timestamp) external view returns (uint256)',
  'function pause() external',
  'function unpause() external',
  'function paused() external view returns (bool)',
  'function blacklistAgent(uint256 agentId, string calldata reason) external',
  'function unblacklistAgent(uint256 agentId) external',
  'function blacklistWallet(address wallet, string calldata reason) external',
  'function unblacklistWallet(address wallet) external',
  'function isAgentBlacklistedActive(uint256 agentId) external view returns (bool)',
  'function isWalletBlacklistedActive(address wallet) external view returns (bool)',
  'error Unauthorized()',
  'error AgentNotFound()',
  'error ProviderNotActive()',
  'error SkillRuleNotFound()',
] as const);
